apiVersion: v1
kind: Secret
metadata:
  name: <your_name_secret>
  namespace: <your_namespace>
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: <"your_mongo_root_username">
  MONGO_ROOT_PASSWORD: <"your_mongo_root_password">
  JWT_SECRET: <"your_jwt_secret">
  MONGO_URI: <"your_mongo_uri">